/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_test_ecgl12 */

#ifndef _Included_com_example_test_ecgl12
#define _Included_com_example_test_ecgl12
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_test_ecgl12
 * Method:    InitProcFunc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_test_ecgl12_InitProcFunc
  (JNIEnv *, jobject);

/*
 * Class:     com_example_test_ecgl12
 * Method:    UsartDataProc
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_example_test_ecgl12_UsartDataProc
  (JNIEnv *, jobject, jbyteArray,jint);

/*
 * Class:     com_example_test_ecgl12
 * Method:    GetResult
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_example_test_ecgl12_GetResult
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_example_test_ecgl12
 * Method:    WitleafRcvCmd1
 * Signature: ()C
 */
JNIEXPORT jboolean JNICALL Java_com_example_test_ecgl12_WitleafRcvCmd1
  (JNIEnv *, jobject);

/*
 * Class:     com_example_test_ecgl12
 * Method:    SatrtEcgAnalysisFlag
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_example_test_ecgl12_SatrtEcgAnalysisFlag
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_example_test_ecgl12
 * Method:    GetFinishEcgAnalysisFlag
 * Signature: ()C
 */
JNIEXPORT jboolean JNICALL Java_com_example_test_ecgl12_GetFinishEcgAnalysisFlag
  (JNIEnv *, jobject);

/*
 * Class:     com_example_test_ecgl12
 * Method:    ClearEcgAnalysisFlag
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_test_ecgl12_ClearEcgAnalysisFlag
  (JNIEnv *, jobject);

/*
 * Class:     com_example_test_ecgl12
 * Method:    DiagnosisAnalysis
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_test_ecgl12_DiagnosisAnalysis
  (JNIEnv *, jobject);


JNIEXPORT jchar JNICALL Java_com_example_test_ecgl12_GetWitleafPacket
  (JNIEnv *, jobject);


JNIEXPORT jintArray JNICALL Java_com_example_test_ecgl12_GetWitleafDataPacket
  (JNIEnv *, jobject);


#ifdef __cplusplus
}
#endif
#endif
